services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: battinala_db

      JWT_SECRET: ffofijioejcvjvjvjdfnfiwfh
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "uv run alembic upgrade head && uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: battinala_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d battinala_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

volumes:
  postgres_data:
