"""add issue priority

Revision ID: 02849c8ce9b5
Revises: b976cbd74697
Create Date: 2026-03-14 22:29:17.373664

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02849c8ce9b5"
down_revision: Union[str, Sequence[str], None] = "b976cbd74697"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the enum type first
    issue_priority_enum = sa.Enum("LOW", "NORMAL", "HIGH", name="issue_priority_enum")
    issue_priority_enum.create(op.get_bind(), checkfirst=True)
    # Add the column using the enum type
    op.add_column(
        "issues",
        sa.Column(
            "issue_priority",
            issue_priority_enum,
            nullable=False,
            server_default="NORMAL",
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("issues", "issue_priority")
    # Drop the enum type
    issue_priority_enum = sa.Enum("LOW", "NORMAL", "HIGH", name="issue_priority_enum")
    issue_priority_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
