"""add reporter id

Revision ID: 0d7eed897e14
Revises: f40b0553a449
Create Date: 2026-04-02 08:02:37.776160

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d7eed897e14"
down_revision: Union[str, Sequence[str], None] = "f40b0553a449"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("issue_reports", sa.Column("reported_by", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "issue_reports", "employees", ["reported_by"], ["employee_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "issue_reports", type_="foreignkey")
    op.drop_column("issue_reports", "reported_by")
    # ### end Alembic commands ###
