"""Team Schema

Revision ID: 12e00c2496dc
Revises: 2ec351933b72
Create Date: 2026-03-04 17:57:51.431077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e00c2496dc'
down_revision: Union[str, Sequence[str], None] = '2ec351933b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('deapartment_id', sa.Integer(), nullable=False),
    sa.Column('base_latitude', sa.String(length=50), nullable=False),
    sa.Column('base_longitude', sa.String(length=50), nullable=False),
    sa.Column('coverage_radius_km', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deapartment_id'], ['departments.department_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('team_name')
    )
    op.create_index(op.f('ix_teams_deapartment_id'), 'teams', ['deapartment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_deapartment_id'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
