"""delete dedicate dep admin table

Revision ID: 2eb918567fc5
Revises: 1074cda7b0d5
Create Date: 2026-03-10 11:38:23.199128

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2eb918567fc5"
down_revision: Union[str, Sequence[str], None] = "1074cda7b0d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    indexes = {ix["name"] for ix in inspector.get_indexes("employees")}
    if op.f("ix_employees_department_id") in indexes:
        op.drop_index(op.f("ix_employees_department_id"), table_name="employees")

    foreign_keys = {fk["name"] for fk in inspector.get_foreign_keys("employees")}
    if op.f("employees_department_id_fkey") in foreign_keys:
        op.drop_constraint(
            op.f("employees_department_id_fkey"),
            "employees",
            type_="foreignkey",
        )

    columns = {col["name"] for col in inspector.get_columns("employees")}
    if "department_id" in columns:
        op.drop_column("employees", "department_id")
    if "department_admins" in inspector.get_table_names():
        op.drop_table("department_admins")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees", sa.Column("department_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        op.f("employees_department_id_fkey"),
        "employees",
        "departments",
        ["department_id"],
        ["department_id"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("ix_employees_department_id"), "employees", ["department_id"], unique=False
    )
    # ### end Alembic commands ###
