"""add department in employee direct

Revision ID: 49041f71a638
Revises: 2eb918567fc5
Create Date: 2026-03-10 11:45:03.527223

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49041f71a638"
down_revision: Union[str, Sequence[str], None] = "2eb918567fc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employees", sa.Column("department_id", sa.Integer(), nullable=False))
    op.create_index(
        op.f("ix_employees_department_id"), "employees", ["department_id"], unique=False
    )
    op.create_foreign_key(
        None, "employees", "departments", ["department_id"], ["department_id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "employees", type_="foreignkey")
    op.drop_index(op.f("ix_employees_department_id"), table_name="employees")
    op.drop_column("employees", "department_id")
    # ### end Alembic commands ###
