"""fix typo in department col name

Revision ID: 661eb1917d41
Revises: 62d7235ac632
Create Date: 2026-03-07 14:25:42.824450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '661eb1917d41'
down_revision: Union[str, Sequence[str], None] = '62d7235ac632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('department_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_teams_deapartment_id'), table_name='teams')
    op.create_index(op.f('ix_teams_department_id'), 'teams', ['department_id'], unique=False)
    op.drop_constraint(op.f('teams_deapartment_id_fkey'), 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'departments', ['department_id'], ['department_id'], ondelete='CASCADE')
    op.drop_column('teams', 'deapartment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('deapartment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key(op.f('teams_deapartment_id_fkey'), 'teams', 'departments', ['deapartment_id'], ['department_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_teams_department_id'), table_name='teams')
    op.create_index(op.f('ix_teams_deapartment_id'), 'teams', ['deapartment_id'], unique=False)
    op.drop_column('teams', 'department_id')
    # ### end Alembic commands ###
