"""fix broken relationships

Revision ID: 669f35b3e626
Revises: 12e00c2496dc
Create Date: 2026-03-04 18:11:15.391806

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "669f35b3e626"
down_revision: Union[str, Sequence[str], None] = "12e00c2496dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("employee_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column(
            "current_status",
            sa.Enum("BUSY", "AVAILABLE", "OFF_DUTY", name="activity_status_enum"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.team_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("employee_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_index(op.f("ix_employees_team_id"), "employees", ["team_id"], unique=False)
    op.create_index(op.f("ix_employees_user_id"), "employees", ["user_id"], unique=True)
    op.create_foreign_key(None, "users", "roles", ["role_id"], ["role_id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_index(op.f("ix_employees_user_id"), table_name="employees")
    op.drop_index(op.f("ix_employees_team_id"), table_name="employees")
    op.drop_table("employees")
    # ### end Alembic commands ###
