"""add phash for attachments

Revision ID: 78e3ed42cec5
Revises: 0d7eed897e14
Create Date: 2026-04-05 07:44:39.483558

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78e3ed42cec5"
down_revision: Union[str, Sequence[str], None] = "0d7eed897e14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attachments", sa.Column("phash", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("attachments", "phash")
    # ### end Alembic commands ###
