"""add issue_label column

Revision ID: b27d4feac8bd
Revises: d06ed1e93345
Create Date: 2026-03-08 20:06:45.869374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b27d4feac8bd'
down_revision: Union[str, Sequence[str], None] = 'd06ed1e93345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('issue_label', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'issues', ['issue_label'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='unique')
    op.drop_column('issues', 'issue_label')
    # ### end Alembic commands ###
