"""otp model

Revision ID: b7c52ef83c91
Revises: 02cf5bd21429
Create Date: 2026-03-06 14:18:08.484019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7c52ef83c91'
down_revision: Union[str, Sequence[str], None] = '02cf5bd21429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('otp_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Enum('sms', 'email', name='otp_channel'), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('signup', 'reset_password', 'anon_report', 'other', name='otp_purpose'), nullable=False),
    sa.Column('otp_salt', sa.LargeBinary(), nullable=False),
    sa.Column('otp_hash', sa.LargeBinary(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resend_available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts_left', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('otp_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
