"""add col for storting dupe id

Revision ID: bb4d23f8222a
Revises: 78e3ed42cec5
Create Date: 2026-04-05 07:52:00.173925

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb4d23f8222a"
down_revision: Union[str, Sequence[str], None] = "78e3ed42cec5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("issues", sa.Column("duplicate_of_issue_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_issues_duplicate_of_issue_id"), "issues", ["duplicate_of_issue_id"], unique=False
    )
    op.create_foreign_key(
        None, "issues", "issues", ["duplicate_of_issue_id"], ["issue_id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "issues", type_="foreignkey")
    op.drop_index(op.f("ix_issues_duplicate_of_issue_id"), table_name="issues")
    op.drop_column("issues", "duplicate_of_issue_id")
    # ### end Alembic commands ###
