"""fixup issue location

Revision ID: c2e94fbf0af5
Revises: 8bdef9a4c38a
Create Date: 2026-03-09 12:18:11.333307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e94fbf0af5'
down_revision: Union[str, Sequence[str], None] = '8bdef9a4c38a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_locations',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(length=50), nullable=False),
    sa.Column('longitude', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.issue_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('issue_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_locations')
    # ### end Alembic commands ###
