"""add contact no

Revision ID: d06ed1e93345
Revises: a4a8c284f1f8
Create Date: 2026-03-08 14:45:08.799565

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d06ed1e93345"
down_revision: Union[str, Sequence[str], None] = "a4a8c284f1f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("issues", sa.Column("contact_no", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("issues", "contact_no")
    # ### end Alembic commands ###
