"""add rejected issue

Revision ID: f40b0553a449
Revises: f66d73a13517
Create Date: 2026-04-01 08:38:59.357496

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f40b0553a449"
down_revision: Union[str, Sequence[str], None] = "f66d73a13517"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rejected_issues",
        sa.Column("reject_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("issue_id", sa.Integer(), nullable=False),
        sa.Column("rejected_by", sa.Integer(), nullable=True),
        sa.Column("auto_rejected", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.issue_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rejected_by"], ["employees.employee_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("reject_id"),
    )
    op.create_index(
        op.f("ix_rejected_issues_issue_id"), "rejected_issues", ["issue_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rejected_issues_issue_id"), table_name="rejected_issues")
    op.drop_table("rejected_issues")
    # ### end Alembic commands ###
