"""make issue id unique

Revision ID: f66d73a13517
Revises: 61e5afa01a4f
Create Date: 2026-03-20 05:31:38.642337

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f66d73a13517"
down_revision: Union[str, Sequence[str], None] = "61e5afa01a4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_issue_reports_issue_id"), table_name="issue_reports")
    op.create_index(op.f("ix_issue_reports_issue_id"), "issue_reports", ["issue_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_issue_reports_issue_id"), table_name="issue_reports")
    op.create_index(op.f("ix_issue_reports_issue_id"), "issue_reports", ["issue_id"], unique=False)
    # ### end Alembic commands ###
